spring.datasource.url=postgresql://shopwave_user:Zq67WgxTbRECo7bCAMpA7CqWjhN1uj70@dpg-d8pnq1sm0tmc73b2qta0-a/shopwave_uecf
spring.datasource.username=krutiktejani
spring.datasource.password=

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=create

server.port=${PORT:8032}